config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :authentication, as: '', path: '' do
    resources :users, only: %i[new create edit update], path: '/register', path_names: { new: '/' }
    resources :sessions, only: %i[new create destroy], path: '/login', path_names: { new: '/'}
  end
  root 'home#welcome'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar
  validates :first_name, :last_name, :email, :username, :phone, :password, presence: { message: :blank }
  normalizes :username, :first_name, :last_name, with: ->(value) { value.downcase }

  validates :password, length: { minimum: 6 }
  validates :email, uniqueness: true,
                    format: {
                      with: /\A([\w+\-.]+)@([a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+)\z/i,
                      message: :invalid
                    }
  normalizes :email, with: ->(email) { email.strip.downcase }

  validates :username, uniqueness: true,
                       length: { in: 3..15 },
                       format: {
                         with: /\A[a-z0-9A-Z]+\z/,
                         message: :invalid
                       }
  validates :phone, uniqueness: true

  enum role: %i[client stylist admin]

  ROLES = %W[client stylist admin]

  ROLES.each do |role|
    define_method "#{role}?" do
      self.role == role
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def authenticate_user!
    redirect_to root_path, alert: 'You must be logged in to do that' unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end

  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end

  def locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
  end
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by("email = :login OR username = :login", { login: params[:login]})
    if @user.authenticate(params[:password])
      login @user
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid login crendentials"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: "Logged out succesfully"
  end
end

app/controllers/authentication/users_controller.rb
# frozen_string_literal: true

class Authentication::UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'User was Succesfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name,
      :email, :username,
      :phone, :password,
      :password_confirmation,
      :role, :avatar
    )
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def welcome; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/authentication/sessions_helper.rb
module Authentication::SessionsHelper
end

app/helpers/authentication/users_helper.rb
# frozen_string_literal: true

module Authentication
  module UsersHelper
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/authentication/users/edit.html.erb
<%= form_with(model: current_user) do |form| %>
  <div data-controller="previews">
    <%= form.label :avatar, 'Tu foto' %>
    <%= form.file_field :avatar, direct_upload: true, data: { previews_target: "input", action: "change->previews#preview" } %>
    <% if current_user.avatar.attached? %>
      <%= image_tag current_user.avatar, class: 'avatar-preview', class: 'avatar-preview', data: { previews_target: "preview"} %>
    <% else %>
      <%= image_tag "placeholder1.png", class: 'avatar-preview', class: 'avatar-preview', data: { previews_target: "preview"} %>
    <% end %>
  </div>

   <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name, required: true %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name, required: true %>
  </div>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username, required: true %>
  </div>
  
  <div>
    <%= form.label :phone %>
    <%= form.text_field :phone, required: true %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authentication/users/new.html.erb
<h1>Register</h1>

<%= form_with(model: @user) do |form| %>
  <% @user.errors.full_messages.each do |message| %>
    <div><%= message %></div>
  <% end %>

  <div data-controller="previews">
    <%= form.label :avatar, 'Tu foto' %>
    <%= form.file_field :avatar, direct_upload: true, data: { previews_target: "input", action: "change->previews#preview" } %>
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, class: 'avatar-preview', class: 'avatar-preview', data: { previews_target: "preview"} %>
    <% else %>
      <%= image_tag "placeholder1.png", class: 'avatar-preview', class: 'avatar-preview', data: { previews_target: "preview"} %>
    <% end %>
  </div>
  
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name, required: true %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name, required: true %>
  </div>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username, required: true %>
  </div>
  
  <div>
    <%= form.label :phone %>
    <%= form.text_field :phone, required: true %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email, required: true %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %> | <%= t('meta_title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if alert || notice %>
  <p>
    <%= alert || notice %>
  </p>
<% end %>

app/views/shared/_header.html.erb
<div>
  <%= link_to root_path do %>
    <h1><%= t('app_name') %></h1>
  <% end %>

  <div class="hidden sm:block">
    <%= render partial: 'shared/items' %>
  </div>    
</div>

app/views/shared/_items.html.erb
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_user_path(current_user) %>
  <%= link_to 'Log out', session_path(current_user), method: :delete, data: {
    turbo_method: :delete,
    turbo_confirm: 'Are you sure?'
  } %>
<% else %>
  <%= link_to 'Log in', new_session_path %>
  <%= link_to 'Sign up', new_user_path %>
<% end %>